### ISSUE TITLE
LASER threshold broken?

### ISSUE THREAD

**Issue by kpu** [hplt-project/OpusCleaner#113]
I did `pip install laserembeddings` then this:
```
Traceback (most recent call last):
  File "/home/kpu/hplt/opuscleaner/lib/python3.11/site-packages/opuscleaner/filters/./laser_similarity.py", line 112, in <module>
    main()
  File "/home/kpu/hplt/opuscleaner/lib/python3.11/site-packages/opuscleaner/filters/./laser_similarity.py", line 100, in main
    scores = _compute_similarity(laser, [tuple(line.rstrip("\r\n").split("\t")[:2]) for line in batch], args.src_lang, args.tgt_lang)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpu/hplt/opuscleaner/lib/python3.11/site-packages/opuscleaner/filters/./laser_similarity.py", line 16, in _compute_similarity
    embeddings_src = laser.embed_sentences([line[0] for line in batch], lang=src_lang)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpu/hplt/opuscleaner/lib/python3.11/site-packages/laserembeddings/laser.py", line 122, in embed_sentences
    return self.bpeSentenceEmbedding.embed_bpe_sentences(bpe_encoded)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpu/hplt/opuscleaner/lib/python3.11/site-packages/laserembeddings/embedding.py", line 49, in embed_bpe_sentences
    return self.encoder.encode_sentences(bpe_sentences)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpu/hplt/opuscleaner/lib/python3.11/site-packages/laserembeddings/encoder.py", line 140, in encode_sentences
    return np.vstack(results)[np.argsort(indices, kind=self.sort_kind)]
           ^^^^^^^^^^^^^^^^^^
  File "/home/kpu/hplt/opuscleaner/lib/python3.11/site-packages/numpy/core/shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at least one array to concatenate
```

**Comment by kpu** [comment]
For what it's worth, corpus is Ubuntu-v14.10.en-mt
