### ISSUE TITLE
Laser filter error: ValueError: could not convert string to float: b''

### ISSUE THREAD

**Issue by eu9ene** [hplt-project/OpusCleaner#156]
Filtering fails on some datasets, for example, en-ru OPUS XLEnt
```
[task 2024-04-17T19:48:57.880Z] [11/12:laser_similarity] Traceback (most recent call last):
[task 2024-04-17T19:48:57.881Z] [11/12:laser_similarity]   File "/builds/worker/.local/lib/python3.10/site-packages/opuscleaner/filters/../threshold.py", line 142, in wrapper
[task 2024-04-17T19:48:57.881Z] [11/12:laser_similarity]     return fn(*args, **kwargs)
[task 2024-04-17T19:48:57.881Z] [11/12:laser_similarity]   File "/builds/worker/.local/lib/python3.10/site-packages/opuscleaner/filters/../threshold.py", line 192, in threshold_scores
[task 2024-04-17T19:48:57.881Z] [11/12:laser_similarity]     item[1].score = float(fchild.readline())
[task 2024-04-17T19:48:57.881Z] [11/12:laser_similarity] ValueError: could not convert string to float: b''
```

**Comment by charliekocsis** [comment]
I'm getting the same error trying to use bicleaner-harddrules with languages en-da (English-Danish), en-nl (English-Dutch) as well as en-pt (English-Portuguese). Perhaps might be all languages. I will try to roll back to potentially earlier version of opuscleaner.

Error:

```
[0/0:bicleaner_hardrules] Traceback (most recent call last):
[0/0:bicleaner_hardrules]   File "/home/user/.local/lib/python3.10/site-packages/opuscleaner/filters/../threshold.py", line 142, in wrapper
[0/0:bicleaner_hardrules]     return fn(*args, **kwargs)
[0/0:bicleaner_hardrules]   File "/home/user/.local/lib/python3.10/site-packages/opuscleaner/filters/../threshold.py", line 192, in threshold_scores
[0/0:bicleaner_hardrules]     item[1].score = float(fchild.readline())
[0/0:bicleaner_hardrules] ValueError: could not convert string to float: b''
[0/0:bicleaner_hardrules] Killed
```
