### ISSUE TITLE
Error when filters is an empty array

### ISSUE THREAD

**Issue by jindrahelcl** [hplt-project/OpusCleaner#90]
```
Traceback (most recent call last):
  File "/lnet/work/people/helcl/virtualenv/hplt/lib/python3.11/site-packages/opuscleaner/clean.py", line 82, in mark_last
    curr_el = next(it)
              ^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lnet/work/people/helcl/virtualenv/hplt/lib/python3.11/site-packages/opuscleaner/clean.py", line 524, in main
    pipeline.run(pool, stdin, stdout, tee=args.tee, basename=basename)
  File "/lnet/work/people/helcl/virtualenv/hplt/lib/python3.11/site-packages/opuscleaner/clean.py", line 224, in run
    for i, (is_last_step, step) in enumerate(mark_last(self.steps)):
RuntimeError: generator raised StopIteration
```

filters.json file:
```
{
  "version": 1,
  "files": [
    "ELRC_2922-v1.en-he.en.gz",
    "ELRC_2922-v1.en-he.he.gz"
  ],
  "filters": []
}
```

**Comment by jindrahelcl** [comment]
This is related to another thing - if you don't apply any filters on a dataset, then it is ignored - i would expect that we get a copy of it and treat it as it is the filtered dataset.

**Comment by jindrahelcl** [comment]
btw, the empty `filters` array probably appears after you add a filter to a dataset and then remove it.
